# 외부 편성표 상품명 전처리

In [1]:
# 모듈 불러오기
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import re

from collections import Counter
import pickle

In [2]:
# 경로 설정
TV2018 = './data/2018_전체_편성표.csv'
TV2019 = './data/2019_전체_편성표.csv'
TV2020 = './data/2020_전체_편성표.csv'

각 연도별 편성표의 상품군 확인
- 2018: '패션·잡화', '여행·레저', '가전·디지털', '화장품·미용', '유아·아동', '생활·주방', '식품·건강', '보험', '"', 'homeshopping', 'tcommerce2'
- 2019: '패션·잡화', '여행·레저', '가전·디지털', '화장품·미용', '유아·아동', '생활·주방', '식품·건강', '보험', '"', 'homeshopping', 'tcommerce2'
- 2020: '패션·잡화', '여행·레저', '가전·디지털', '화장품·미용', '유아·아동', '생활·주방', '식품·건강', '보험', '"', 'homeshopping', 'tcommerce2'

In [3]:
# 데이터 로드
schedule_2018 = pd.read_csv(TV2018)
schedule_2019 = pd.read_csv(TV2019)
schedule_2020 = pd.read_csv(TV2020)

In [4]:
# 상품명 null 확인
display(schedule_2018.loc[schedule_2018['product name'].isnull()])
display(schedule_2019.loc[schedule_2019['product name'].isnull()])
display(schedule_2020.loc[schedule_2020['product name'].isnull()])

,홈쇼핑채널,상품군,홈쇼핑/티커머스,start time,end time,price,product name
233985,shopnt,패션·잡화,tcommerce2,2018-10-16 04:48:00,2018-10-16 05:48:00,88900,NaN
234012,shopnt,패션·잡화,tcommerce2,2018-10-16 05:48:00,2018-10-16 06:47:00,98000,NaN
234013,shopnt,패션·잡화,tcommerce2,2018-10-16 05:48:00,2018-10-16 06:47:00,98000,NaN
234048,shopnt,패션·잡화,tcommerce2,2018-10-16 06:47:00,2018-10-16 07:47:00,48000,NaN
234121,shopnt,보험,tcommerce2,2018-10-16 08:46:00,2018-10-16 09:46:00,0,NaN
234167,shopnt,식품·건강,tcommerce2,2018-10-16 09:46:00,2018-10-16 10:45:00,44900,NaN
234198,shopnt,가전·디지털,tcommerce2,2018-10-16 10:45:00,2018-10-16 11:45:00,258000,NaN
234199,shopnt,가전·디지털,tcommerce2,2018-10-16 10:45:00,2018-10-16 11:45:00,228000,NaN
234200,shopnt,가전·디지털,tcommerce2,2018-10-16 10:45:00,2018-10-16 11:45:00,150000,NaN
234201,shopnt,가전·디지털,tcommerce2,2018-10-16 10:45:00,2018-10-16 11:45:00,115000,NaN
234274,shopnt,가전·디지털,tcommerce2,2018-10-16 11:45:00,2018-10-16 12:44:00,57000,NaN
234397,shopnt,화장품·미용,tcommerce2,2018-10-16 14:43:00,2018-10-16 15:43:00,58800,NaN
234464,shopnt,식품·건강,tcommerce2,2018-10-16 16:42:00,2018-10-16 17:42:00,68000,NaN
234491,shopnt,가전·디지털,tcommerce2,2018-10-16 17:42:00,2018-10-16 18:41:00,117000,NaN
234492,shopnt,가전·디지털,tcommerce2,2018-10-16 17:42:00,2018-10-16 18:41:00,98000,NaN
234493,shopnt,가전·디지털,tcommerce2,2018-10-16 17:42:00,2018-10-16 18:41:00,87000,NaN
234494,shopnt,가전·디지털,tcommerce2,2018-10-16 17:42:00,2018-10-16 18:41:00,64000,NaN
234551,shopnt,가전·디지털,tcommerce2,2018-10-16 18:41:00,2018-10-16 19:41:00,207000,NaN
234552,shopnt,가전·디지털,tcommerce2,2018-10-16 18:41:00,2018-10-16 19:41:00,197000,NaN
234667,shopnt,가전·디지털,tcommerce2,2018-10-16 21:40:00,2018-10-16 22:39:00,258000,NaN
234668,shopnt,가전·디지털,tcommerce2,2018-10-16 21:40:00,2018-10-16 22:39:00,228000,NaN
234669,shopnt,가전·디지털,tcommerce2,2018-10-16 21:40:00,2018-10-16 22:39:00,150000,NaN
234670,shopnt,가전·디지털,tcommerce2,2018-10-16 21:40:00,2018-10-16 22:39:00,115000,NaN
234707,shopnt,패션·잡화,tcommerce2,2018-10-16 23:39:00,2018-10-17 00:38:00,298000,NaN
236591,shopnt,가전·디지털,tcommerce2,2018-10-19 01:44:00,2018-10-19 02:43:00,78000,NaN
237160,shopnt,가전·디지털,tcommerce2,2018-10-19 15:41:00,2018-10-19 16:40:00,78000,NaN
246042,shopnt,가전·디지털,tcommerce2,2018-10-29 12:46:00,2018-10-29 13:45:00,78000,NaN
248931,shopnt,가전·디지털,tcommerce2,2018-11-01 13:28:00,2018-11-01 14:27:00,78000,NaN
254008,shopnt,가전·디지털,tcommerce2,2018-11-07 03:35:00,2018-11-07 03:54:00,78000,NaN
258663,shopnt,가전·디지털,tcommerce2,2018-11-12 02:33:00,2018-11-12 03:36:00,78000,NaN
261270,shopnt,가전·디지털,tcommerce2,2018-11-15 02:19:00,2018-11-15 03:19:00,78000,NaN
261295,shopnt,가전·디지털,tcommerce2,2018-11-15 03:19:00,2018-11-15 03:24:00,78000,NaN
262124,shopnt,가전·디지털,tcommerce2,2018-11-16 01:27:00,2018-11-16 02:27:00,78000,NaN
265596,shopnt,가전·디지털,tcommerce2,2018-11-20 00:56:00,2018-11-20 01:36:00,78000,NaN
268441,shopnt,가전·디지털,tcommerce2,2018-11-23 03:35:00,2018-11-23 03:54:00,78000,NaN
271210,shopnt,가전·디지털,tcommerce2,2018-11-26 03:34:00,2018-11-26 03:54:00,78000,NaN
273363,shopnt,패션·잡화,tcommerce2,2018-11-28 08:56:00,2018-11-28 09:56:00,678000,NaN
279446,shopnt,가전·디지털,tcommerce2,2018-12-05 03:30:00,2018-12-05 03:50:00,78000,NaN
281213,shopnt,가전·디지털,tcommerce2,2018-12-07 03:35:00,2018-12-07 03:55:00,78000,NaN
284801,shopnt,가전·디지털,tcommerce2,2018-12-11 03:38:00,2018-12-11 03:38:00,78000,NaN
292927,shopnt,패션·잡화,tcommerce2,2018-12-20 05:53:00,2018-12-20 06:52:00,68000,NaN
296493,shopnt,패션·잡화,tcommerce2,2018-12-24 05:45:00,2018-12-24 06:45:00,68000,NaN
297072,shopnt,패션·잡화,tcommerce2,2018-12-24 21:37:00,2018-12-24 22:37:00,68000,NaN
298257,shopnt,가전·디지털,tcommerce2,2018-12-26 04:51:00,2018-12-26 05:50:00,115000,NaN
298402,shopnt,가전·디지털,tcommerce2,2018-12-26 08:49:00,2018-12-26 09:48:00,115000,NaN
300911,shopnt,패션·잡화,tcommerce2,2018-12-29 03:44:00,2018-12-29 03:44:00,68000,NaN
302807,shopnt,패션·잡화,tcommerce2,2018-12-31 06:49:00,2018-12-31 07:48:00,68000,NaN

,홈쇼핑채널,상품군,홈쇼핑/티커머스,start time,end time,price,product name
3363,shopnt,패션·잡화,tcommerce2,2019-01-04 20:52:00,2019-01-04 21:51:00,68900,NaN
3364,shopnt,패션·잡화,tcommerce2,2019-01-04 20:52:00,2019-01-04 21:51:00,68900,NaN
9693,wshop,여행·레저,tcommerce2,2019-01-12 00:25:00,2019-01-12 01:26:00,398000,NaN
9784,wshop,화장품·미용,tcommerce2,2019-01-12 03:26:00,2019-01-12 05:12:00,59000,NaN
9902,wshop,화장품·미용,tcommerce2,2019-01-12 07:12:00,2019-01-12 08:13:00,59000,NaN
...,...,...,...,...,...,...,...
136862,shopnt,패션·잡화,tcommerce2,2019-05-22 08:54:00,2019-05-22 09:54:00,1240000,NaN
136864,shopnt,패션·잡화,tcommerce2,2019-05-22 08:54:00,2019-05-22 09:54:00,1570000,NaN
136865,shopnt,패션·잡화,tcommerce2,2019-05-22 08:54:00,2019-05-22 09:54:00,1070000,NaN
139343,shopnt,패션·잡화,tcommerce2,2019-05-24 18:46:00,2019-05-24 19:45:00,138000,NaN
150505,shopnt,패션·잡화,tcommerce2,2019-06-04 09:47:00,2019-06-04 10:46:00,70200,NaN

,홈쇼핑채널,상품군,홈쇼핑/티커머스,start time,end time,price,product name
137017,gsshop,homeshopping,homeshopping,2020-05-09 17:20:00,2020-05-09 17:40:00,0,NaN

In [5]:
# 데이터 통합
schedule = pd.concat([schedule_2018, schedule_2019, schedule_2020])
schedule = schedule.dropna().reset_index(drop=True)
schedule

,홈쇼핑채널,상품군,홈쇼핑/티커머스,start time,end time,price,product name
0,hmallplus,패션·잡화,tcommerce2,2018-01-01 00:00:00,2018-01-01 00:59:00,139000,푸마 무브 셀 브라 리뉴얼6차 19종 팩키지
1,lotteonetv,여행·레저,tcommerce2,2018-01-01 00:00:00,2018-01-01 01:00:00,399000,●세부 3박 4일/5일
2,bshop,가전·디지털,tcommerce2,2018-01-01 00:01:00,2018-01-01 00:42:00,0,[SKT] 갤럭시 S8 (SK스토아 개국 이벤트)
3,bshop,가전·디지털,tcommerce2,2018-01-01 00:01:00,2018-01-01 00:42:00,0,[SKT] 갤럭시 S8+ (SK스토아 개국 이벤트)
4,lottemall,화장품·미용,homeshopping,2018-01-01 00:03:00,2018-01-01 01:00:00,148000,[1stC] 프리미엄 퍼스트씨 퓨어 비타민C 세럼 블랙 시너지크림 완벽더블 패키지
...,...,...,...,...,...,...,...
937432,hmall,가전·디지털,homeshopping,2020-08-31 23:55:00,2020-09-01 01:00:00,1690000,[65][1등급] LG 울트라 HD TV 163cm [65UN7850KNA] (사은...
937433,hmall,가전·디지털,homeshopping,2020-08-31 23:55:00,2020-09-01 01:00:00,1290000,[55][1등급] LG 울트라 HD TV 138cm [55UN7850KNA] (사은...
937434,lottemall,화장품·미용,homeshopping,2020-08-31 23:55:00,2020-09-01 01:00:00,227000,[더블구성 8개월관리분+무료체험 2개] 질경이 2X 이너밸런스 총 4박스(총 32개...
937435,lottemall,화장품·미용,homeshopping,2020-08-31 23:55:00,2020-09-01 01:00:00,118000,[싱글구성 4개월관리분+무료체험 1개] 질경이 2X 이너밸런스 총 2박스(총 16개...
937436,nsmall,가전·디지털,homeshopping,2020-08-31 23:55:00,2020-09-01 01:00:00,2440000,LG 디오스 5도어 이지아이스(F873SS31H)+WMF 멀티 컴팩트 초고속 블랜더...

## 상품명 정제

 문자(알파벳, 한글), 숫자만 남기고 모두 제거한다.

In [6]:
# 상품명 정제
schedule['product name clean'] = schedule['product name'].str.replace('[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9]', ' ')
schedule.head(2)

,홈쇼핑채널,상품군,홈쇼핑/티커머스,start time,end time,price,product name,product name clean
0,hmallplus,패션·잡화,tcommerce2,2018-01-01 00:00:00,2018-01-01 00:59:00,139000,푸마 무브 셀 브라 리뉴얼6차 19종 팩키지,푸마 무브 셀 브라 리뉴얼6차 19종 팩키지
1,lotteonetv,여행·레저,tcommerce2,2018-01-01 00:00:00,2018-01-01 01:00:00,399000,●세부 3박 4일/5일,세부 3박 4일 5일

In [7]:
# 정제된 상품명 저장
schedule.to_csv('./data/편성표(18-20)_상품명_정제.csv', index=False, encoding='utf-8-sig')

## 상품명 단어 사전 만들기

In [8]:
# 상품명 corpus 만들기
products = schedule['product name clean'].tolist()
corpus = []
for p in products:
    corpus.extend(p.strip().split())
print(products[:10])
print(corpus[:10])

['푸마 무브 셀 브라 리뉴얼6차 19종 팩키지', ' 세부 3박 4일 5일', ' SKT  갤럭시 S8  SK스토아 개국 이벤트 ', ' SKT  갤럭시 S8   SK스토아 개국 이벤트 ', ' 1stC  프리미엄 퍼스트씨 퓨어 비타민C 세럼 블랙 시너지크림 완벽더블 패키지', ' 1stC  프리미엄 퍼스트씨 퓨어 비타민C 세럼 최대용량 패키지', ' 1stC  프리미엄 퍼스트씨 퓨어 비타민C 세럼 블랙 시너지크림 패키지', '  1st C   프리미엄 퍼스트씨 퓨어 비타민씨 10병   찰떡궁합 시너지크림 1종   무료체험분 1매', ' 1stC  쿠션 특별기획  프리미엄 퍼스트씨 퓨어 비타민씨 8병   퍼스트씨 컬러베일쿠션   무료체험분', ' 비지트인뉴욕콜렉션  퓨어 캐시미어 롱코트  캐시미어30  울60  ']
['푸마', '무브', '셀', '브라', '리뉴얼6차', '19종', '팩키지', '세부', '3박', '4일']

In [11]:
# 어휘집 생성
container = Counter(corpus)
vocabulary = dict(container.most_common())
with open('./data/외부편성표상품명어휘집.pickle', 'wb') as f:
    pickle.dump(vocabulary, f, pickle.HIGHEST_PROTOCOL)

In [38]:
# csv 저장
vocab_df = pd.Dat

AttributeError: module 'pandas' has no attribute 'DataFram'